# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /time-manager

# Copy package.json and package-lock.json to the working directory
COPY package.json ./
COPY package-lock.json ./


# Install project dependencies
RUN npm install

# Copy the entire project directory into the container
COPY . ./

# Build the Vue.js application for production
# RUN npm run build

RUN chmod +x base_start.sh

# Define the command to start the application
CMD ["sh","base_start.sh"]